### ISSUE TITLE
Rename classes to *Client

### ISSUE THREAD

**Issue by bcb** [bcb/jsonrpcclient#19]
Proposing to rename the "server" modules and classes,  to "client";

- HTTPServer becomes HTTPClient
- ZMQServer becomes ZMQClient
- TornadoServer becomes TornadoClient

Example code:

```python
>>> from jsonrpcclient.http_client import HTTPClient
>>> HTTPClient('http://cats.com/').request('speak')
```

The plan would be to deprecate the old names by subclassing.

**Comment by saaj** [comment]
I absolutely agree that `HTTPServer` and friends are confusing names. Especially when you open a module that says `from jsonrpcclient.http_server import HTTPServer`. Like "does this module really start a JSON RPC server?!". That happened to me a few days ago. And through looking at the code I realised it's just a proxy. Because there is `__getattr__` dunder that makes it mimic the remote object that exposes some methods, it's a [remote proxy][1]. But it's obvious that it's also a client for JSON RPC protocol a little bellow the call stack. So your proposal is okay as well. 

[1]: https://en.wikipedia.org/wiki/Proxy_pattern

**Comment by bcb** [comment]
Exactly, all the attributes and methods relate to the server. But it makes just as much sense calling `client.request()` as `server.request()`.

Ok I'll rename them, and show a deprecation warning if the old names are used.
